name: Build APK with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build APK using official Kivy Buildozer Docker image
        run: |
          docker run --rm \
            -e CI=1 \
            -v ${{ github.workspace }}:/app \
            -w /app \
            kivy/buildozer:latest \
            buildozer android debug --no-pty

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sniper-apk
          path: bin/*.apk